name: dartx
description: Superpowers for Dart. Collection of useful static extension methods.
version: 1.2.0
homepage: https://github.com/leisim/dartx

environment:
  sdk: '^3.4.4'

dependencies:
  characters: ^1.3.0
  collection: ^1.19.0
  crypto: ^3.0.3
  meta: ^1.15.0
  path: ^1.9.0
  time: ^2.1.4

dev_dependencies:
  fake_async: ^1.3.1
  lints: ^4.0.0
  test: ^1.25.7
